--- 
- 
  hosts: digitalocean
  name: wp_deploy_digitalocean
  remote_user: root
  become: true
  vars_prompt: 
    - 
      name: procced
      prompt: "this will deploy lamp &wordpress on the server (y|n)"
   
  pre_tasks: 
    - name: tell user on progress
      debug: msg="exiting..............." 
      when: procced != 'y' 

    - name: exitnode
      meta: end_play 
      when: procced != 'y'
      
    - name: install apache2
      become: yes
      apt:
        name: apache2
        state: present
        
    
    - name: install phpndextension
      become: yes
      apt:
        state: present 
        pkg:
          - php-curl
          - php-gd
          - php-mbstring
          - php-xml
          - php-xmlrpc
          - php-soap
          - php-intl
          - php-zip
          - php 
          - libapache2-mod-php 
          - php-mysql


  roles: 
    - role: mariadb
      when: procced == 'y'
    - role: wordpress
      when: procced == 'y'



#  on finish you will need to : do nthing.


#2: look in here for settings:   nano /var/www/wordpress/wp-config.php the user and pass


