---
# tasks file for wordpress

-  name: mysql_user 
   become: true
   mysql_user: 
    login_user: "root"
    login_password: ""
    login_unix_socket: /var/run/mysqld/mysqld.sock 
    name: wpuser
    password: password
    priv: '*.*:ALL'
    state: present 

- name: create db for wp
  mysql_db:
    login_user: wpuser
    login_password: "{{ mysql_root_password  }}"
    # login_unix_socket: /var/run/mysqld/mysqld.sock #makes an error without it
    name: wordpress
    state: present 
    collation: utf8_general_ci   

-  name: download wp.tar
   get_url:
     url: https://wordpress.org/latest.tar.gz
     dest: /tmp/wordpress.tar.gz
     validate_certs: no

-  name: extarct
   unarchive: 
     src: /tmp/wordpress.tar.gz
     dest: /var/www/
     copy: no

- name: Update default Apache site
  lineinfile: 
    dest=/etc/apache2/sites-enabled/000-default.conf 
    regexp="(.)+DocumentRoot /var/www/html"
    line="DocumentRoot /var/www/wordpress"
  notify:
    - restart apache

- name:  sample-config file
  command: mv /var/www/wordpress/wp-config-sample.php /var/www/wordpress/wp-config.php creates=/var/www/wordpress/wp-config.php
  

